import isNullOrUndefined from 'src/shared/lib/isNullOrUndefined';

interface IActivityGoal {
  id?: string;
  activityId: string;
  targetPerWeek: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export default class ActivityGoal {
  props: IActivityGoal;

  private constructor(props: IActivityGoal) {
    this.props = props;
  }

  get id(): string | undefined {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('Activity Goal has not been persisted yet');
    }
    return this.props.id;
  }

  get activityId(): string {
    return this.props.activityId;
  }

  get targetPerWeek(): number {
    return this.props.targetPerWeek;
  }

  public isPersisted(): this is IActivityGoal & { id: string } {
    return !isNullOrUndefined(this.props.id);
  }

  public ensurePersisted(): asserts this is IActivityGoal & { id: string } {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('Activity Goal must be persisted before this operation');
    }
  }

  public changeTargetPerWeek(targetPerWeek: number) {
    if (isNullOrUndefined(targetPerWeek) || !isValidTarget(targetPerWeek)) {
      throw new Error('Goal Failed Validation');
    }
    this.props.targetPerWeek = targetPerWeek;
  }

  private static validate(props: IActivityGoal) {
    if (
      isNullOrUndefined(props.activityId) ||
      isNullOrUndefined(props.targetPerWeek) ||
      !isValidTarget(props.targetPerWeek)
    ) {
      throw new Error('Goal Failed Validation');
    }
  }

  /*
   * Create for the first time.
   * Will have no id yet.
   */
  public static createNew(props: IActivityGoal) {
    this.validate(props);
    return new ActivityGoal(props);
  }

  /**
   * Create after the ID has been generated by the database.
   * aka create from data returned by the database.
   */
  public static reconstitute(props: IActivityGoal): ActivityGoal {
    if (!props.id) {
      throw new Error('ID is required for reconstituting activity goal');
    }
    this.validate(props);
    return new ActivityGoal(props);
  }
}

function isValidTarget(targetPerWeek: number): boolean {
  return (
    Number.isInteger(targetPerWeek) && targetPerWeek >= 1 && targetPerWeek <= 7
  );
}
