import isNullOrUndefined from 'src/shared/lib/isNullOrUndefined';
import UserEmail from './value-objects/UserEmail';
import UserPassword from './value-objects/UserPassword';

interface IUser {
  id?: string;
  email: UserEmail;
  password: UserPassword;
  createdAt?: Date;
  updatedAt?: Date;
}

export default class User {
  props: IUser;

  private constructor(props: IUser) {
    this.props = props;
  }

  get id(): string | undefined {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('User has not been persisted yet');
    }
    return this.props.id;
  }

  get email(): UserEmail {
    return this.props.email;
  }

  get password(): UserPassword {
    return this.props.password;
  }

  public isPersisted(): this is IUser & { id: string } {
    return !isNullOrUndefined(this.props.id);
  }

  public ensurePersisted(): asserts this is IUser & { id: string } {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('User must be persisted before this operation');
    }
  }

  private static validate(props: IUser) {
    if (!props.email) {
      throw new Error('Cant create user, email cant be blank');
    }
  }

  /*
   * Create the user the first time during registration.
   * User will have no id yet.
   */
  public static createNew(props: Omit<IUser, 'id'>): User {
    this.validate(props);
    return new User(props);
  }

  /**
   * Create after the ID has been generated by the database.
   * aka create from user data returned by the database.
   */
  public static reconstitute(props: IUser): User {
    if (!props.id) {
      throw new Error('ID is required for reconstituting user');
    }
    this.validate(props);
    return new User(props);
  }
}
