import ActivityTicker from './activityTicker.vo';
import isNullOrUndefined from 'src/shared/lib/isNullOrUndefined';

interface IActivity {
  id?: string;
  userId: string;
  name: string;
  ticker?: ActivityTicker;
  interval: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export default class Activity {
  props: IActivity;

  private constructor(props: IActivity) {
    this.props = props;
  }

  get id(): string | undefined {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('Activity has not been persisted yet');
    }
    return this.props.id;
  }

  get userId(): string {
    return this.props.userId;
  }

  get name(): string {
    return this.props.name;
  }

  get ticker(): ActivityTicker | undefined {
    return this.props.ticker;
  }

  get interval(): number {
    return this.props.interval;
  }

  public isPersisted(): this is IActivity & { id: string } {
    return !isNullOrUndefined(this.props.id);
  }

  public ensurePersisted(): asserts this is IActivity & { id: string } {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('Activity must be persisted before this operation');
    }
  }

  private static validate(props: IActivity) {
    if (
      isNullOrUndefined(props.userId) ||
      isNullOrUndefined(props.name) ||
      isNullOrUndefined(props.interval)
    ) {
      // throw new ActivityCreateFailedValidationError();
      throw new Error('Activity Failed Validation');
    }
  }

  /*
   * Create for the first time.
   * Will have no id yet.
   */
  public static createNew(props: IActivity) {
    this.validate(props);
    return new Activity(props);
  }

  /**
   * Create after the ID has been generated by the database.
   * aka create from data returned by the database.
   */
  public static reconstitute(props: IActivity): Activity {
    if (!props.id) {
      throw new Error('ID is required for reconstituting activity');
    }
    this.validate(props);
    return new Activity(props);
  }
}
