import isNullOrUndefined from 'src/shared/lib/isNullOrUndefined';

interface IActivityEvent {
  id?: string;
  activityId: string;
  date: string;
}
export default class ActivityEvent {
  props: IActivityEvent;

  private constructor(props: IActivityEvent) {
    this.props = props;
  }

  get id(): string | undefined {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('Activity Event has not been persisted yet');
    }
    return this.props.id;
  }

  get date(): string {
    return this.props.date;
  }

  get activityId(): string {
    return this.props.activityId;
  }

  public isPersisted(): this is IActivityEvent & { id: string } {
    return !isNullOrUndefined(this.props.id);
  }

  public ensurePersisted(): asserts this is IActivityEvent & { id: string } {
    if (isNullOrUndefined(this.props.id)) {
      throw new Error('User must be persisted before this operation');
    }
  }

  private static validate(props: IActivityEvent) {
    if (!props.date) {
      throw new Error('Date cant be blank');
    }

    const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(props.date);
    if (!match) {
      throw new Error('Date must be in YYYY-MM-DD format');
    }
  }

  /*
   * Create for the first time.
   * Will have no id yet.
   */
  public static createNew(props: IActivityEvent) {
    this.validate(props);
    return new ActivityEvent(props);
  }

  /**
   * Create after the ID has been generated by the database.
   * aka create from data returned by the database.
   */
  public static reconstitute(props: IActivityEvent): ActivityEvent {
    if (!props.id) {
      throw new Error('ID is required for reconstituting activity event');
    }
    this.validate(props);
    return new ActivityEvent(props);
  }
}
