/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProtecRouteImport } from './routes/protec'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityEditActivityIdRouteImport } from './routes/activity/edit.$activityId'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecRoute = ProtecRouteImport.update({
  id: '/protec',
  path: '/protec',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityEditActivityIdRoute = ActivityEditActivityIdRouteImport.update({
  id: '/activity/edit/$activityId',
  path: '/activity/edit/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/protec': typeof ProtecRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/activity/edit/$activityId': typeof ActivityEditActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/protec': typeof ProtecRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/activity/edit/$activityId': typeof ActivityEditActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/protec': typeof ProtecRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/activity/edit/$activityId': typeof ActivityEditActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/protec'
    | '/register'
    | '/timeline'
    | '/activity/edit/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/protec'
    | '/register'
    | '/timeline'
    | '/activity/edit/$activityId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/protec'
    | '/register'
    | '/timeline'
    | '/activity/edit/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProtecRoute: typeof ProtecRoute
  RegisterRoute: typeof RegisterRoute
  TimelineRoute: typeof TimelineRoute
  ActivityEditActivityIdRoute: typeof ActivityEditActivityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protec': {
      id: '/protec'
      path: '/protec'
      fullPath: '/protec'
      preLoaderRoute: typeof ProtecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/edit/$activityId': {
      id: '/activity/edit/$activityId'
      path: '/activity/edit/$activityId'
      fullPath: '/activity/edit/$activityId'
      preLoaderRoute: typeof ActivityEditActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProtecRoute: ProtecRoute,
  RegisterRoute: RegisterRoute,
  TimelineRoute: TimelineRoute,
  ActivityEditActivityIdRoute: ActivityEditActivityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
